version: '{build}'
image: Visual Studio 2017
build_script:
- ps: .\build.ps1
artifacts:
- path: .\artifacts\*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  api_key:
    secure: xYKR6UZf0gwhlj9vaF2V350eapAief4eRn5nAoCl5RGmByvS5ct1ZWNaXbAaqOMG
  skip_symbols: false